# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: filer.proto
"""
Generated protocol buffer code.
"""
from google.protobuf import descriptor as _descriptor  # type: ignore
from google.protobuf import descriptor_pool as _descriptor_pool  # type: ignore
from google.protobuf import symbol_database as _symbol_database  # type: ignore
from google.protobuf.internal import builder as _builder  # type: ignore

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0b\x66iler.proto\x12\x08\x66iler_pb">\n\x1bLookupDirectoryEntryRequest\x12\x11\n\tdirectory\x18\x01'
    b" \x01(\t\x12\x0c\n\x04name\x18\x02"
    b' \x01(\t">\n\x1cLookupDirectoryEntryResponse\x12\x1e\n\x05\x65ntry\x18\x01'
    b' \x01(\x0b\x32\x0f.filer_pb.Entry"}\n\x12ListEntriesRequest\x12\x11\n\tdirectory\x18\x01'
    b" \x01(\t\x12\x0e\n\x06prefix\x18\x02 \x01(\t\x12\x19\n\x11startFromFileName\x18\x03"
    b" \x01(\t\x12\x1a\n\x12inclusiveStartFrom\x18\x04 \x01(\x08\x12\r\n\x05limit\x18\x05"
    b' \x01(\r"5\n\x13ListEntriesResponse\x12\x1e\n\x05\x65ntry\x18\x01'
    b' \x01(\x0b\x32\x0f.filer_pb.Entry"\x83\x01\n\x0bRemoteEntry\x12\x14\n\x0cstorage_name\x18\x01'
    b" \x01(\t\x12\x1d\n\x15last_local_sync_ts_ns\x18\x02"
    b" \x01(\x03\x12\x14\n\x0cremote_e_tag\x18\x03 \x01(\t\x12\x14\n\x0cremote_mtime\x18\x04"
    b" \x01(\x03\x12\x13\n\x0bremote_size\x18\x05"
    b' \x01(\x03"\xde\x02\n\x05\x45ntry\x12\x0c\n\x04name\x18\x01'
    b" \x01(\t\x12\x14\n\x0cis_directory\x18\x02 \x01(\x08\x12#\n\x06\x63hunks\x18\x03"
    b" \x03(\x0b\x32\x13.filer_pb.FileChunk\x12,\n\nattributes\x18\x04"
    b" \x01(\x0b\x32\x18.filer_pb.FuseAttributes\x12/\n\x08\x65xtended\x18\x05"
    b" \x03(\x0b\x32\x1d.filer_pb.Entry.ExtendedEntry\x12\x14\n\x0chard_link_id\x18\x07"
    b" \x01(\x0c\x12\x19\n\x11hard_link_counter\x18\x08 \x01(\x05\x12\x0f\n\x07\x63ontent\x18\t"
    b" \x01(\x0c\x12+\n\x0cremote_entry\x18\n"
    b" \x01(\x0b\x32\x15.filer_pb.RemoteEntry\x12\r\n\x05quota\x18\x0b"
    b" \x01(\x03\x1a/\n\rExtendedEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02"
    b' \x01(\x0c:\x02\x38\x01"8\n\tFullEntry\x12\x0b\n\x03\x64ir\x18\x01'
    b" \x01(\t\x12\x1e\n\x05\x65ntry\x18\x02"
    b' \x01(\x0b\x32\x0f.filer_pb.Entry"\xbe\x01\n\x11\x45ventNotification\x12"\n\told_entry\x18\x01'
    b' \x01(\x0b\x32\x0f.filer_pb.Entry\x12"\n\tnew_entry\x18\x02'
    b" \x01(\x0b\x32\x0f.filer_pb.Entry\x12\x15\n\rdelete_chunks\x18\x03"
    b" \x01(\x08\x12\x17\n\x0fnew_parent_path\x18\x04"
    b" \x01(\t\x12\x1d\n\x15is_from_other_cluster\x18\x05 \x01(\x08\x12\x12\n\nsignatures\x18\x06"
    b' \x03(\x05"\x84\x02\n\tFileChunk\x12\x0f\n\x07\x66ile_id\x18\x01'
    b" \x01(\t\x12\x0e\n\x06offset\x18\x02 \x01(\x03\x12\x0c\n\x04size\x18\x03"
    b" \x01(\x04\x12\x16\n\x0emodified_ts_ns\x18\x04 \x01(\x03\x12\r\n\x05\x65_tag\x18\x05"
    b" \x01(\t\x12\x16\n\x0esource_file_id\x18\x06 \x01(\t\x12\x1d\n\x03\x66id\x18\x07"
    b" \x01(\x0b\x32\x10.filer_pb.FileId\x12$\n\nsource_fid\x18\x08"
    b" \x01(\x0b\x32\x10.filer_pb.FileId\x12\x12\n\ncipher_key\x18\t"
    b" \x01(\x0c\x12\x15\n\ris_compressed\x18\n \x01(\x08\x12\x19\n\x11is_chunk_manifest\x18\x0b"
    b' \x01(\x08"8\n\x11\x46ileChunkManifest\x12#\n\x06\x63hunks\x18\x01'
    b' \x03(\x0b\x32\x13.filer_pb.FileChunk"=\n\x06\x46ileId\x12\x11\n\tvolume_id\x18\x01'
    b" \x01(\r\x12\x10\n\x08\x66ile_key\x18\x02 \x01(\x04\x12\x0e\n\x06\x63ookie\x18\x03"
    b' \x01(\x07"\xf7\x01\n\x0e\x46useAttributes\x12\x11\n\tfile_size\x18\x01'
    b" \x01(\x04\x12\r\n\x05mtime\x18\x02 \x01(\x03\x12\x11\n\tfile_mode\x18\x03"
    b" \x01(\r\x12\x0b\n\x03uid\x18\x04 \x01(\r\x12\x0b\n\x03gid\x18\x05"
    b" \x01(\r\x12\x0e\n\x06\x63rtime\x18\x06 \x01(\x03\x12\x0c\n\x04mime\x18\x07"
    b" \x01(\t\x12\x0f\n\x07ttl_sec\x18\n \x01(\x05\x12\x11\n\tuser_name\x18\x0b"
    b" \x01(\t\x12\x12\n\ngroup_name\x18\x0c \x03(\t\x12\x16\n\x0esymlink_target\x18\r"
    b" \x01(\t\x12\x0b\n\x03md5\x18\x0e \x01(\x0c\x12\x0c\n\x04rdev\x18\x10"
    b" \x01(\r\x12\r\n\x05inode\x18\x11"
    b' \x01(\x04"\xaf\x01\n\x12\x43reateEntryRequest\x12\x11\n\tdirectory\x18\x01'
    b" \x01(\t\x12\x1e\n\x05\x65ntry\x18\x02"
    b" \x01(\x0b\x32\x0f.filer_pb.Entry\x12\x0e\n\x06o_excl\x18\x03"
    b" \x01(\x08\x12\x1d\n\x15is_from_other_cluster\x18\x04 \x01(\x08\x12\x12\n\nsignatures\x18\x05"
    b" \x03(\x05\x12#\n\x1bskip_check_parent_directory\x18\x06"
    b' \x01(\x08"$\n\x13\x43reateEntryResponse\x12\r\n\x05\x65rror\x18\x01'
    b' \x01(\t"z\n\x12UpdateEntryRequest\x12\x11\n\tdirectory\x18\x01'
    b" \x01(\t\x12\x1e\n\x05\x65ntry\x18\x02"
    b" \x01(\x0b\x32\x0f.filer_pb.Entry\x12\x1d\n\x15is_from_other_cluster\x18\x03"
    b" \x01(\x08\x12\x12\n\nsignatures\x18\x04"
    b' \x03(\x05"\x15\n\x13UpdateEntryResponse"b\n\x14\x41ppendToEntryRequest\x12\x11\n\tdirectory\x18\x01'
    b" \x01(\t\x12\x12\n\nentry_name\x18\x02 \x01(\t\x12#\n\x06\x63hunks\x18\x03"
    b' \x03(\x0b\x32\x13.filer_pb.FileChunk"\x17\n\x15\x41ppendToEntryResponse"\xb6\x01\n\x12\x44\x65leteEntryRequest\x12\x11\n\tdirectory\x18\x01'
    b" \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x16\n\x0eis_delete_data\x18\x04"
    b" \x01(\x08\x12\x14\n\x0cis_recursive\x18\x05"
    b" \x01(\x08\x12\x1e\n\x16ignore_recursive_error\x18\x06"
    b" \x01(\x08\x12\x1d\n\x15is_from_other_cluster\x18\x07 \x01(\x08\x12\x12\n\nsignatures\x18\x08"
    b' \x03(\x05"$\n\x13\x44\x65leteEntryResponse\x12\r\n\x05\x65rror\x18\x01'
    b' \x01(\t"\x80\x01\n\x18\x41tomicRenameEntryRequest\x12\x15\n\rold_directory\x18\x01'
    b" \x01(\t\x12\x10\n\x08old_name\x18\x02 \x01(\t\x12\x15\n\rnew_directory\x18\x03"
    b" \x01(\t\x12\x10\n\x08new_name\x18\x04 \x01(\t\x12\x12\n\nsignatures\x18\x05"
    b' \x03(\x05"\x1b\n\x19\x41tomicRenameEntryResponse"\x80\x01\n\x18StreamRenameEntryRequest\x12\x15\n\rold_directory\x18\x01'
    b" \x01(\t\x12\x10\n\x08old_name\x18\x02 \x01(\t\x12\x15\n\rnew_directory\x18\x03"
    b" \x01(\t\x12\x10\n\x08new_name\x18\x04 \x01(\t\x12\x12\n\nsignatures\x18\x05"
    b' \x03(\x05"v\n\x19StreamRenameEntryResponse\x12\x11\n\tdirectory\x18\x01'
    b" \x01(\t\x12\x37\n\x12\x65vent_notification\x18\x02"
    b" \x01(\x0b\x32\x1b.filer_pb.EventNotification\x12\r\n\x05ts_ns\x18\x03"
    b' \x01(\x03"\xb5\x01\n\x13\x41ssignVolumeRequest\x12\r\n\x05\x63ount\x18\x01'
    b" \x01(\x05\x12\x12\n\ncollection\x18\x02 \x01(\t\x12\x13\n\x0breplication\x18\x03"
    b" \x01(\t\x12\x0f\n\x07ttl_sec\x18\x04 \x01(\x05\x12\x13\n\x0b\x64\x61ta_center\x18\x05"
    b" \x01(\t\x12\x0c\n\x04path\x18\x06 \x01(\t\x12\x0c\n\x04rack\x18\x07"
    b" \x01(\t\x12\x11\n\tdata_node\x18\t \x01(\t\x12\x11\n\tdisk_type\x18\x08"
    b' \x01(\t"\xa2\x01\n\x14\x41ssignVolumeResponse\x12\x0f\n\x07\x66ile_id\x18\x01'
    b" \x01(\t\x12\r\n\x05\x63ount\x18\x04 \x01(\x05\x12\x0c\n\x04\x61uth\x18\x05"
    b" \x01(\t\x12\x12\n\ncollection\x18\x06 \x01(\t\x12\x13\n\x0breplication\x18\x07"
    b" \x01(\t\x12\r\n\x05\x65rror\x18\x08 \x01(\t\x12$\n\x08location\x18\t"
    b' \x01(\x0b\x32\x12.filer_pb.Location")\n\x13LookupVolumeRequest\x12\x12\n\nvolume_ids\x18\x01'
    b' \x03(\t"2\n\tLocations\x12%\n\tlocations\x18\x01'
    b' \x03(\x0b\x32\x12.filer_pb.Location"S\n\x08Location\x12\x0b\n\x03url\x18\x01'
    b" \x01(\t\x12\x12\n\npublic_url\x18\x02 \x01(\t\x12\x11\n\tgrpc_port\x18\x03"
    b" \x01(\r\x12\x13\n\x0b\x64\x61ta_center\x18\x04"
    b' \x01(\t"\xa9\x01\n\x14LookupVolumeResponse\x12G\n\rlocations_map\x18\x01'
    b" \x03(\x0b\x32\x30.filer_pb.LookupVolumeResponse.LocationsMapEntry\x1aH\n\x11LocationsMapEntry\x12\x0b\n\x03key\x18\x01"
    b' \x01(\t\x12"\n\x05value\x18\x02'
    b' \x01(\x0b\x32\x13.filer_pb.Locations:\x02\x38\x01"\x1a\n\nCollection\x12\x0c\n\x04name\x18\x01'
    b' \x01(\t"S\n\x15\x43ollectionListRequest\x12\x1e\n\x16include_normal_volumes\x18\x01'
    b" \x01(\x08\x12\x1a\n\x12include_ec_volumes\x18\x02"
    b' \x01(\x08"C\n\x16\x43ollectionListResponse\x12)\n\x0b\x63ollections\x18\x01'
    b' \x03(\x0b\x32\x14.filer_pb.Collection"-\n\x17\x44\x65leteCollectionRequest\x12\x12\n\ncollection\x18\x01'
    b' \x01(\t"\x1a\n\x18\x44\x65leteCollectionResponse"\\\n\x11StatisticsRequest\x12\x13\n\x0breplication\x18\x01'
    b" \x01(\t\x12\x12\n\ncollection\x18\x02 \x01(\t\x12\x0b\n\x03ttl\x18\x03"
    b" \x01(\t\x12\x11\n\tdisk_type\x18\x04"
    b' \x01(\t"O\n\x12StatisticsResponse\x12\x12\n\ntotal_size\x18\x04'
    b" \x01(\x04\x12\x11\n\tused_size\x18\x05 \x01(\x04\x12\x12\n\nfile_count\x18\x06"
    b' \x01(\x04"2\n\x0bPingRequest\x12\x0e\n\x06target\x18\x01'
    b" \x01(\t\x12\x13\n\x0btarget_type\x18\x02"
    b' \x01(\t"S\n\x0cPingResponse\x12\x15\n\rstart_time_ns\x18\x01'
    b" \x01(\x03\x12\x16\n\x0eremote_time_ns\x18\x02 \x01(\x03\x12\x14\n\x0cstop_time_ns\x18\x03"
    b' \x01(\x03"\x1e\n\x1cGetFilerConfigurationRequest"\x92\x02\n\x1dGetFilerConfigurationResponse\x12\x0f\n\x07masters\x18\x01'
    b" \x03(\t\x12\x13\n\x0breplication\x18\x02 \x01(\t\x12\x12\n\ncollection\x18\x03"
    b" \x01(\t\x12\x0e\n\x06max_mb\x18\x04 \x01(\r\x12\x13\n\x0b\x64ir_buckets\x18\x05"
    b" \x01(\t\x12\x0e\n\x06\x63ipher\x18\x07 \x01(\x08\x12\x11\n\tsignature\x18\x08"
    b" \x01(\x05\x12\x17\n\x0fmetrics_address\x18\t \x01(\t\x12\x1c\n\x14metrics_interval_sec\x18\n"
    b" \x01(\x05\x12\x0f\n\x07version\x18\x0b \x01(\t\x12\x12\n\ncluster_id\x18\x0c"
    b" \x01(\t\x12\x13\n\x0b\x66iler_group\x18\r"
    b' \x01(\t"\xd0\x01\n\x18SubscribeMetadataRequest\x12\x13\n\x0b\x63lient_name\x18\x01'
    b" \x01(\t\x12\x13\n\x0bpath_prefix\x18\x02 \x01(\t\x12\x10\n\x08since_ns\x18\x03"
    b" \x01(\x03\x12\x11\n\tsignature\x18\x04 \x01(\x05\x12\x15\n\rpath_prefixes\x18\x06"
    b" \x03(\t\x12\x11\n\tclient_id\x18\x07 \x01(\x05\x12\x10\n\x08until_ns\x18\x08"
    b" \x01(\x03\x12\x14\n\x0c\x63lient_epoch\x18\t \x01(\x05\x12\x13\n\x0b\x64irectories\x18\n"
    b' \x03(\t"v\n\x19SubscribeMetadataResponse\x12\x11\n\tdirectory\x18\x01'
    b" \x01(\t\x12\x37\n\x12\x65vent_notification\x18\x02"
    b" \x01(\x0b\x32\x1b.filer_pb.EventNotification\x12\r\n\x05ts_ns\x18\x03"
    b' \x01(\x03"C\n\x08LogEntry\x12\r\n\x05ts_ns\x18\x01'
    b" \x01(\x03\x12\x1a\n\x12partition_key_hash\x18\x02 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x03"
    b' \x01(\x0c"J\n\x14KeepConnectedRequest\x12\x0c\n\x04name\x18\x01'
    b" \x01(\t\x12\x11\n\tgrpc_port\x18\x02 \x01(\r\x12\x11\n\tresources\x18\x03"
    b' \x03(\t"\x17\n\x15KeepConnectedResponse"\'\n\x13LocateBrokerRequest\x12\x10\n\x08resource\x18\x01'
    b' \x01(\t"\x9d\x01\n\x14LocateBrokerResponse\x12\r\n\x05\x66ound\x18\x01'
    b" \x01(\x08\x12:\n\tresources\x18\x02"
    b" \x03(\x0b\x32'.filer_pb.LocateBrokerResponse.Resource\x1a:\n\x08Resource\x12\x16\n\x0egrpc_addresses\x18\x01"
    b" \x01(\t\x12\x16\n\x0eresource_count\x18\x02"
    b' \x01(\x05"\x1b\n\x0cKvGetRequest\x12\x0b\n\x03key\x18\x01'
    b' \x01(\x0c"-\n\rKvGetResponse\x12\r\n\x05value\x18\x01 \x01(\x0c\x12\r\n\x05\x65rror\x18\x02'
    b' \x01(\t"*\n\x0cKvPutRequest\x12\x0b\n\x03key\x18\x01 \x01(\x0c\x12\r\n\x05value\x18\x02'
    b' \x01(\x0c"\x1e\n\rKvPutResponse\x12\r\n\x05\x65rror\x18\x01'
    b' \x01(\t"\xb1\x02\n\tFilerConf\x12\x0f\n\x07version\x18\x01'
    b" \x01(\x05\x12/\n\tlocations\x18\x02"
    b" \x03(\x0b\x32\x1c.filer_pb.FilerConf.PathConf\x1a\xe1\x01\n\x08PathConf\x12\x17\n\x0flocation_prefix\x18\x01"
    b" \x01(\t\x12\x12\n\ncollection\x18\x02 \x01(\t\x12\x13\n\x0breplication\x18\x03"
    b" \x01(\t\x12\x0b\n\x03ttl\x18\x04 \x01(\t\x12\x11\n\tdisk_type\x18\x05"
    b" \x01(\t\x12\r\n\x05\x66sync\x18\x06 \x01(\x08\x12\x1b\n\x13volume_growth_count\x18\x07"
    b" \x01(\r\x12\x11\n\tread_only\x18\x08 \x01(\x08\x12\x13\n\x0b\x64\x61ta_center\x18\t"
    b" \x01(\t\x12\x0c\n\x04rack\x18\n \x01(\t\x12\x11\n\tdata_node\x18\x0b"
    b' \x01(\t"I\n&CacheRemoteObjectToLocalClusterRequest\x12\x11\n\tdirectory\x18\x01'
    b" \x01(\t\x12\x0c\n\x04name\x18\x02"
    b" \x01(\t\"I\n'CacheRemoteObjectToLocalClusterResponse\x12\x1e\n\x05\x65ntry\x18\x01"
    b' \x01(\x0b\x32\x0f.filer_pb.Entry"[\n\x0bLockRequest\x12\x0c\n\x04name\x18\x01'
    b" \x01(\t\x12\x17\n\x0fseconds_to_lock\x18\x02 \x01(\x03\x12\x13\n\x0brenew_token\x18\x03"
    b" \x01(\t\x12\x10\n\x08is_moved\x18\x04"
    b' \x01(\x08"D\n\x0cLockResponse\x12\x13\n\x0brenew_token\x18\x01'
    b" \x01(\t\x12\x10\n\x08moved_to\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03"
    b' \x01(\t"D\n\rUnlockRequest\x12\x0c\n\x04name\x18\x01'
    b" \x01(\t\x12\x13\n\x0brenew_token\x18\x02 \x01(\t\x12\x10\n\x08is_moved\x18\x03"
    b' \x01(\x08"1\n\x0eUnlockResponse\x12\r\n\x05\x65rror\x18\x01'
    b' \x01(\t\x12\x10\n\x08moved_to\x18\x02 \x01(\t"@\n\x04Lock\x12\x0c\n\x04name\x18\x01'
    b" \x01(\t\x12\x13\n\x0brenew_token\x18\x02 \x01(\t\x12\x15\n\rexpired_at_ns\x18\x03"
    b' \x01(\x03"5\n\x14TransferLocksRequest\x12\x1d\n\x05locks\x18\x01'
    b' \x03(\x0b\x32\x0e.filer_pb.Lock"\x17\n\x15TransferLocksResponse2\xa5\x0f\n\x0cSeaweedFiler\x12g\n\x14LookupDirectoryEntry\x12%.filer_pb.LookupDirectoryEntryRequest\x1a&.filer_pb.LookupDirectoryEntryResponse"\x00\x12N\n\x0bListEntries\x12\x1c.filer_pb.ListEntriesRequest\x1a\x1d.filer_pb.ListEntriesResponse"\x00\x30\x01\x12L\n\x0b\x43reateEntry\x12\x1c.filer_pb.CreateEntryRequest\x1a\x1d.filer_pb.CreateEntryResponse"\x00\x12L\n\x0bUpdateEntry\x12\x1c.filer_pb.UpdateEntryRequest\x1a\x1d.filer_pb.UpdateEntryResponse"\x00\x12R\n\rAppendToEntry\x12\x1e.filer_pb.AppendToEntryRequest\x1a\x1f.filer_pb.AppendToEntryResponse"\x00\x12L\n\x0b\x44\x65leteEntry\x12\x1c.filer_pb.DeleteEntryRequest\x1a\x1d.filer_pb.DeleteEntryResponse"\x00\x12^\n\x11\x41tomicRenameEntry\x12".filer_pb.AtomicRenameEntryRequest\x1a#.filer_pb.AtomicRenameEntryResponse"\x00\x12`\n\x11StreamRenameEntry\x12".filer_pb.StreamRenameEntryRequest\x1a#.filer_pb.StreamRenameEntryResponse"\x00\x30\x01\x12O\n\x0c\x41ssignVolume\x12\x1d.filer_pb.AssignVolumeRequest\x1a\x1e.filer_pb.AssignVolumeResponse"\x00\x12O\n\x0cLookupVolume\x12\x1d.filer_pb.LookupVolumeRequest\x1a\x1e.filer_pb.LookupVolumeResponse"\x00\x12U\n\x0e\x43ollectionList\x12\x1f.filer_pb.CollectionListRequest\x1a'
    b' .filer_pb.CollectionListResponse"\x00\x12[\n\x10\x44\x65leteCollection\x12!.filer_pb.DeleteCollectionRequest\x1a".filer_pb.DeleteCollectionResponse"\x00\x12I\n\nStatistics\x12\x1b.filer_pb.StatisticsRequest\x1a\x1c.filer_pb.StatisticsResponse"\x00\x12\x37\n\x04Ping\x12\x15.filer_pb.PingRequest\x1a\x16.filer_pb.PingResponse"\x00\x12j\n\x15GetFilerConfiguration\x12&.filer_pb.GetFilerConfigurationRequest\x1a\'.filer_pb.GetFilerConfigurationResponse"\x00\x12`\n\x11SubscribeMetadata\x12".filer_pb.SubscribeMetadataRequest\x1a#.filer_pb.SubscribeMetadataResponse"\x00\x30\x01\x12\x65\n\x16SubscribeLocalMetadata\x12".filer_pb.SubscribeMetadataRequest\x1a#.filer_pb.SubscribeMetadataResponse"\x00\x30\x01\x12:\n\x05KvGet\x12\x16.filer_pb.KvGetRequest\x1a\x17.filer_pb.KvGetResponse"\x00\x12:\n\x05KvPut\x12\x16.filer_pb.KvPutRequest\x1a\x17.filer_pb.KvPutResponse"\x00\x12\x88\x01\n\x1f\x43\x61\x63heRemoteObjectToLocalCluster\x12\x30.filer_pb.CacheRemoteObjectToLocalClusterRequest\x1a\x31.filer_pb.CacheRemoteObjectToLocalClusterResponse"\x00\x12\x37\n\x04Lock\x12\x15.filer_pb.LockRequest\x1a\x16.filer_pb.LockResponse"\x00\x12=\n\x06Unlock\x12\x17.filer_pb.UnlockRequest\x1a\x18.filer_pb.UnlockResponse"\x00\x12R\n\rTransferLocks\x12\x1e.filer_pb.TransferLocksRequest\x1a\x1f.filer_pb.TransferLocksResponse"\x00\x42O\n\x10seaweedfs.clientB\nFilerProtoZ/github.com/seaweedfs/seaweedfs/weed/pb/filer_pbb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "filer_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS is False:
    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = (
        b"\n\020seaweedfs.clientB\nFilerProtoZ/github.com/seaweedfs/seaweedfs/weed/pb/filer_pb"
    )
    _ENTRY_EXTENDEDENTRY._options = None
    _ENTRY_EXTENDEDENTRY._serialized_options = b"8\001"
    _LOOKUPVOLUMERESPONSE_LOCATIONSMAPENTRY._options = None
    _LOOKUPVOLUMERESPONSE_LOCATIONSMAPENTRY._serialized_options = b"8\001"
    _globals["_LOOKUPDIRECTORYENTRYREQUEST"]._serialized_start = 25
    _globals["_LOOKUPDIRECTORYENTRYREQUEST"]._serialized_end = 87
    _globals["_LOOKUPDIRECTORYENTRYRESPONSE"]._serialized_start = 89
    _globals["_LOOKUPDIRECTORYENTRYRESPONSE"]._serialized_end = 151
    _globals["_LISTENTRIESREQUEST"]._serialized_start = 153
    _globals["_LISTENTRIESREQUEST"]._serialized_end = 278
    _globals["_LISTENTRIESRESPONSE"]._serialized_start = 280
    _globals["_LISTENTRIESRESPONSE"]._serialized_end = 333
    _globals["_REMOTEENTRY"]._serialized_start = 336
    _globals["_REMOTEENTRY"]._serialized_end = 467
    _globals["_ENTRY"]._serialized_start = 470
    _globals["_ENTRY"]._serialized_end = 820
    _globals["_ENTRY_EXTENDEDENTRY"]._serialized_start = 773
    _globals["_ENTRY_EXTENDEDENTRY"]._serialized_end = 820
    _globals["_FULLENTRY"]._serialized_start = 822
    _globals["_FULLENTRY"]._serialized_end = 878
    _globals["_EVENTNOTIFICATION"]._serialized_start = 881
    _globals["_EVENTNOTIFICATION"]._serialized_end = 1071
    _globals["_FILECHUNK"]._serialized_start = 1074
    _globals["_FILECHUNK"]._serialized_end = 1334
    _globals["_FILECHUNKMANIFEST"]._serialized_start = 1336
    _globals["_FILECHUNKMANIFEST"]._serialized_end = 1392
    _globals["_FILEID"]._serialized_start = 1394
    _globals["_FILEID"]._serialized_end = 1455
    _globals["_FUSEATTRIBUTES"]._serialized_start = 1458
    _globals["_FUSEATTRIBUTES"]._serialized_end = 1705
    _globals["_CREATEENTRYREQUEST"]._serialized_start = 1708
    _globals["_CREATEENTRYREQUEST"]._serialized_end = 1883
    _globals["_CREATEENTRYRESPONSE"]._serialized_start = 1885
    _globals["_CREATEENTRYRESPONSE"]._serialized_end = 1921
    _globals["_UPDATEENTRYREQUEST"]._serialized_start = 1923
    _globals["_UPDATEENTRYREQUEST"]._serialized_end = 2045
    _globals["_UPDATEENTRYRESPONSE"]._serialized_start = 2047
    _globals["_UPDATEENTRYRESPONSE"]._serialized_end = 2068
    _globals["_APPENDTOENTRYREQUEST"]._serialized_start = 2070
    _globals["_APPENDTOENTRYREQUEST"]._serialized_end = 2168
    _globals["_APPENDTOENTRYRESPONSE"]._serialized_start = 2170
    _globals["_APPENDTOENTRYRESPONSE"]._serialized_end = 2193
    _globals["_DELETEENTRYREQUEST"]._serialized_start = 2196
    _globals["_DELETEENTRYREQUEST"]._serialized_end = 2378
    _globals["_DELETEENTRYRESPONSE"]._serialized_start = 2380
    _globals["_DELETEENTRYRESPONSE"]._serialized_end = 2416
    _globals["_ATOMICRENAMEENTRYREQUEST"]._serialized_start = 2419
    _globals["_ATOMICRENAMEENTRYREQUEST"]._serialized_end = 2547
    _globals["_ATOMICRENAMEENTRYRESPONSE"]._serialized_start = 2549
    _globals["_ATOMICRENAMEENTRYRESPONSE"]._serialized_end = 2576
    _globals["_STREAMRENAMEENTRYREQUEST"]._serialized_start = 2579
    _globals["_STREAMRENAMEENTRYREQUEST"]._serialized_end = 2707
    _globals["_STREAMRENAMEENTRYRESPONSE"]._serialized_start = 2709
    _globals["_STREAMRENAMEENTRYRESPONSE"]._serialized_end = 2827
    _globals["_ASSIGNVOLUMEREQUEST"]._serialized_start = 2830
    _globals["_ASSIGNVOLUMEREQUEST"]._serialized_end = 3011
    _globals["_ASSIGNVOLUMERESPONSE"]._serialized_start = 3014
    _globals["_ASSIGNVOLUMERESPONSE"]._serialized_end = 3176
    _globals["_LOOKUPVOLUMEREQUEST"]._serialized_start = 3178
    _globals["_LOOKUPVOLUMEREQUEST"]._serialized_end = 3219
    _globals["_LOCATIONS"]._serialized_start = 3221
    _globals["_LOCATIONS"]._serialized_end = 3271
    _globals["_LOCATION"]._serialized_start = 3273
    _globals["_LOCATION"]._serialized_end = 3356
    _globals["_LOOKUPVOLUMERESPONSE"]._serialized_start = 3359
    _globals["_LOOKUPVOLUMERESPONSE"]._serialized_end = 3528
    _globals["_LOOKUPVOLUMERESPONSE_LOCATIONSMAPENTRY"]._serialized_start = 3456
    _globals["_LOOKUPVOLUMERESPONSE_LOCATIONSMAPENTRY"]._serialized_end = 3528
    _globals["_COLLECTION"]._serialized_start = 3530
    _globals["_COLLECTION"]._serialized_end = 3556
    _globals["_COLLECTIONLISTREQUEST"]._serialized_start = 3558
    _globals["_COLLECTIONLISTREQUEST"]._serialized_end = 3641
    _globals["_COLLECTIONLISTRESPONSE"]._serialized_start = 3643
    _globals["_COLLECTIONLISTRESPONSE"]._serialized_end = 3710
    _globals["_DELETECOLLECTIONREQUEST"]._serialized_start = 3712
    _globals["_DELETECOLLECTIONREQUEST"]._serialized_end = 3757
    _globals["_DELETECOLLECTIONRESPONSE"]._serialized_start = 3759
    _globals["_DELETECOLLECTIONRESPONSE"]._serialized_end = 3785
    _globals["_STATISTICSREQUEST"]._serialized_start = 3787
    _globals["_STATISTICSREQUEST"]._serialized_end = 3879
    _globals["_STATISTICSRESPONSE"]._serialized_start = 3881
    _globals["_STATISTICSRESPONSE"]._serialized_end = 3960
    _globals["_PINGREQUEST"]._serialized_start = 3962
    _globals["_PINGREQUEST"]._serialized_end = 4012
    _globals["_PINGRESPONSE"]._serialized_start = 4014
    _globals["_PINGRESPONSE"]._serialized_end = 4097
    _globals["_GETFILERCONFIGURATIONREQUEST"]._serialized_start = 4099
    _globals["_GETFILERCONFIGURATIONREQUEST"]._serialized_end = 4129
    _globals["_GETFILERCONFIGURATIONRESPONSE"]._serialized_start = 4132
    _globals["_GETFILERCONFIGURATIONRESPONSE"]._serialized_end = 4406
    _globals["_SUBSCRIBEMETADATAREQUEST"]._serialized_start = 4409
    _globals["_SUBSCRIBEMETADATAREQUEST"]._serialized_end = 4617
    _globals["_SUBSCRIBEMETADATARESPONSE"]._serialized_start = 4619
    _globals["_SUBSCRIBEMETADATARESPONSE"]._serialized_end = 4737
    _globals["_LOGENTRY"]._serialized_start = 4739
    _globals["_LOGENTRY"]._serialized_end = 4806
    _globals["_KEEPCONNECTEDREQUEST"]._serialized_start = 4808
    _globals["_KEEPCONNECTEDREQUEST"]._serialized_end = 4882
    _globals["_KEEPCONNECTEDRESPONSE"]._serialized_start = 4884
    _globals["_KEEPCONNECTEDRESPONSE"]._serialized_end = 4907
    _globals["_LOCATEBROKERREQUEST"]._serialized_start = 4909
    _globals["_LOCATEBROKERREQUEST"]._serialized_end = 4948
    _globals["_LOCATEBROKERRESPONSE"]._serialized_start = 4951
    _globals["_LOCATEBROKERRESPONSE"]._serialized_end = 5108
    _globals["_LOCATEBROKERRESPONSE_RESOURCE"]._serialized_start = 5050
    _globals["_LOCATEBROKERRESPONSE_RESOURCE"]._serialized_end = 5108
    _globals["_KVGETREQUEST"]._serialized_start = 5110
    _globals["_KVGETREQUEST"]._serialized_end = 5137
    _globals["_KVGETRESPONSE"]._serialized_start = 5139
    _globals["_KVGETRESPONSE"]._serialized_end = 5184
    _globals["_KVPUTREQUEST"]._serialized_start = 5186
    _globals["_KVPUTREQUEST"]._serialized_end = 5228
    _globals["_KVPUTRESPONSE"]._serialized_start = 5230
    _globals["_KVPUTRESPONSE"]._serialized_end = 5260
    _globals["_FILERCONF"]._serialized_start = 5263
    _globals["_FILERCONF"]._serialized_end = 5568
    _globals["_FILERCONF_PATHCONF"]._serialized_start = 5343
    _globals["_FILERCONF_PATHCONF"]._serialized_end = 5568
    _globals["_CACHEREMOTEOBJECTTOLOCALCLUSTERREQUEST"]._serialized_start = 5570
    _globals["_CACHEREMOTEOBJECTTOLOCALCLUSTERREQUEST"]._serialized_end = 5643
    _globals["_CACHEREMOTEOBJECTTOLOCALCLUSTERRESPONSE"]._serialized_start = 5645
    _globals["_CACHEREMOTEOBJECTTOLOCALCLUSTERRESPONSE"]._serialized_end = 5718
    _globals["_LOCKREQUEST"]._serialized_start = 5720
    _globals["_LOCKREQUEST"]._serialized_end = 5811
    _globals["_LOCKRESPONSE"]._serialized_start = 5813
    _globals["_LOCKRESPONSE"]._serialized_end = 5881
    _globals["_UNLOCKREQUEST"]._serialized_start = 5883
    _globals["_UNLOCKREQUEST"]._serialized_end = 5951
    _globals["_UNLOCKRESPONSE"]._serialized_start = 5953
    _globals["_UNLOCKRESPONSE"]._serialized_end = 6002
    _globals["_LOCK"]._serialized_start = 6004
    _globals["_LOCK"]._serialized_end = 6068
    _globals["_TRANSFERLOCKSREQUEST"]._serialized_start = 6070
    _globals["_TRANSFERLOCKSREQUEST"]._serialized_end = 6123
    _globals["_TRANSFERLOCKSRESPONSE"]._serialized_start = 6125
    _globals["_TRANSFERLOCKSRESPONSE"]._serialized_end = 6148
    _globals["_SEAWEEDFILER"]._serialized_start = 6151
    _globals["_SEAWEEDFILER"]._serialized_end = 8108
# @@protoc_insertion_point(module_scope)
